### ISSUE TITLE
Question: feature that mislav/bump-homebrew-formula-action is missing?

### ISSUE THREAD

**Issue by jasonkarns** [dawidd6/action-homebrew-bump-formula#1]
What does this action do that https://github.com/mislav/bump-homebrew-formula-action doesn't?

**Comment by dawidd6** [comment]
This Action basically wraps `brew bump-formula-pr` command, so it's closer to the "official" process of bumping formulae.

Also mislav's Action does not seem to support bumping formulae that pull the source directly from git, rather than extracting source tarball.
