### ISSUE TITLE
inplace replace failed: expected replacement of `v0.8.0` when latest version is `v0.8.8`

### ISSUE THREAD

**Issue by kdheepak** [dawidd6/action-homebrew-bump-formula#18]
Thanks for making this github action!

I'm trying to update this formula on a release: https://github.com/Homebrew/homebrew-core/blob/master/Formula/taskwarrior-tui.rb

It worked as expected once. However, the next couple of times I made a tag I got the following error.

https://github.com/kdheepak/taskwarrior-tui/runs/1305070251#step:2:58

```plaintext
HEAD is now at f3cf85f100 orc-tools 1.6.5
==> Downloading v0.8.8.tar.gz
==> Downloading from codeload.github.com/kdheepak/taskwarrior-tui/tar.gz/v0.8.8
Warning: Cannot verify integrity of f398f3541aadf5fc7f3cdcf40e3935da0c4d852d03ed06859d1ba321562b2535--taskwarrior-tui-0.8.8.tar.gz
Error: inreplace failed
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/taskwarrior-tui.rb:
  expected replacement of /https:\/\/github\.com\/kdheepak\/taskwarrior\-tui\/archive\/v0\.8\.0\.tar\.gz/ with "v0.8.8.tar.gz"
  expected replacement of "15a2195dde970f369b5b1e346a087c72581142525765baeffe8d54b95824bae0" with "36e3a1feaa48bc04b4d49f936a35da83006566fd9abda43811edb51246a1ce73"
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:288:in `safe_system': Failure while executing; `brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\(https://github.com/dawidd6/action-homebrew-bump-formula\) --version=0.8.8 --url=v0.8.8.tar.gz taskwarrior-tui` exited with 1. (ErrorDuringExecution)
A checksum was not provided for this resource.
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:28:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:116:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:17:in `<main>'
For your reference the SHA-256 is: 36e3a1feaa48bc04b4d49f936a35da83006566fd9abda43811edb51246a1ce73
==> replace /https:\/\/github\.com\/kdheepak\/taskwarrior\-tui\/archive\/v0\.8\.0\.tar\.gz/ with "v0.8.8.tar.gz"
==> replace "15a2195dde970f369b5b1e346a087c72581142525765baeffe8d54b95824bae0" with "36e3a1feaa48bc04b4d49f936a35da83006566fd9abda43811edb51246a1ce73"
```

It appears as though the old repo is not updated (?). I don't fully understand what is going on here. I get the same error when I try to re-run the workflow.

I also tried to delete the fork of homebrew-core, and the workflow creates a fork as expected, but I get a different error in that case.

https://github.com/kdheepak/taskwarrior-tui/runs/1306371332

This says it is a permissions error, which I don't know why it would be the case. It is able to create the fork and it worked when I tried to update the formula before. See this PR for reference: https://github.com/Homebrew/homebrew-core/pull/63451.

**Comment by kdheepak** [comment]
For what it is worth, I tried it locally and it works fine. This is the PR I created from my local machine: https://github.com/Homebrew/homebrew-core/pull/63476

I have the token configured correctly as per the documentation on the README.md of this repository on the taskwarrior-tui github repository as well.

**Comment by dawidd6** [comment]
> For what it is worth, I tried it locally and it works fine.

On macOS?

**Comment by dawidd6** [comment]
This is actually a bug in brew, but I couldn't pinpoint it. This happens when linuxbrew-core is behind homebrew-core in terms of changes to a formula.

**Comment by dawidd6** [comment]
A workaround is to run this Action on macos-latest image:
https://github.com/kdheepak/taskwarrior-tui/blob/2e0b17a6d7e90ebdef75f06c0dc2f0738420c650/.github/workflows/ci.yml#L111

**Comment by kdheepak** [comment]
Ah! Yes, that makes sense. I didn't realize that linuxbrew-core was a separate repo.

> On macOS?

Yes, I was running locally on my mac.

I'll use a macos-latest image! Thanks for the suggestion.
