### ISSUE TITLE
Help with updating formula

### ISSUE THREAD

**Issue by Woile** [dawidd6/action-homebrew-bump-formula#25]
Hello, thanks for this project!

In our project we are trying to use it, I'm no Mac user but some of our users want to have it available on Mac.

I was wondering if you could help me with the following error:
https://github.com/commitizen-tools/commitizen/runs/1844420295?check_suite_focus=true

Our current workflow is as this:
action1 creates tag
on tag creation, action2 publishes our package to python's pip
when action2 is complete, we trigger the publish to homebrew, but it fails.

Any kind of help would be useful.
Thanks!

**Comment by dawidd6** [comment]
This formula fetches source from pypi I see. Formulae like that one aren't supported currently. Maybe I'll have a look later.

**Comment by Woile** [comment]
Awesome, thanks! 👍🏻

**Comment by dawidd6** [comment]
This should now work OOTB. Release `v3.7.0` and `v3` tag contain fixes/improvements for formulae that pull source from PyPi. Also one formula of this type is now tested on CI.

https://github.com/dawidd6/action-homebrew-bump-formula/compare/v3.6.1...v3.7.0

**Comment by Woile** [comment]
Great news, thanks a lot. Next release I'll let you know 💪🏻

**Comment by Woile** [comment]
Hello @dawidd6 reporting some feedback! 
We released a new version and we see this error: https://github.com/commitizen-tools/commitizen/runs/2052902961?check_suite_focus=true

```
/usr/local/Homebrew/Library/Homebrew/version.rb:605:in `empty?': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.3/lib/active_support/core_ext/object/blank.rb:19:in `blank?'
	from /usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:54:in `pypi_info'
	from /usr/local/Homebrew/Library/Homebrew/utils/pypi.rb:115:in `update_pypi_url'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:102:in `<module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:18:in `<main>'
Error: Process completed with exit code 1.
```

Thanks!

**Comment by dawidd6** [comment]
Looking at the Action inputs:

```
with:
    token: ***
    formula: commitizen
    tag: refs/heads/master
    revision: 3b591f02c8c0008adb57775a17ece7a9b0d6f230
```

`tag` is wrong. It's because you are triggering the workflow on `workflow_run` event which runs on `master` branch. This is not correct. Consider either passing manually the proper tag or set `livecheck` input to `true` if you are certain that at the time the workflow is running the PyPi package is already updated to newest version, because `brew livecheck` queries PyPi (by default for this particular formula).

**Comment by dawidd6** [comment]
Any news. Can this issue be closed?

**Comment by Woile** [comment]
Hey dawid, you can close it for now, the issue now is me getting the last released version, but I haven't had time to dig into it. if I have any new issue with this action I'll come back. Thanks again for the help 👍🏻

**Comment by Woile** [comment]
Seems to be workiiiing!! https://github.com/Homebrew/homebrew-core/pull/79161 💪🏻
