### ISSUE TITLE
Could not read Password, No such device or address

### ISSUE THREAD

**Issue by khos2ow** [dawidd6/action-homebrew-bump-formula#28]
I'm getting `fatal: could not read Password for 'https:// ***@github.com': No such device or address` error while trying to run the action. Full log:

```
 [bump-terraform-docs-0.11.1 fffdefbf24d] terraform-docs 0.11.1
 1 file changed, 2 insertions(+), 2 deletions(-)
fatal: could not read Password for 'https:// ***@github.com': No such device or address
Error: Failure while executing; `git push --set-upstream https://\ ***@github.com/tf-docs-bot/homebrew-core.git bump-terraform-docs-0.11.1:bump-terraform-docs-0.11.1` exited with 128.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:321:in `safe_system': Failure while executing; `brew bump-formula-pr --no-audit --no-browse --message=\[\`action-homebrew-bump-formula\`\]\(https://github.com/dawidd6/action-homebrew-bump-formula\) --version=0.11.1 --url=https://github.com/terraform-docs/terraform-docs/archive/v0.11.1.tar.gz terraform-docs` exited with 1. (ErrorDuringExecution)
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.5.1/main.rb:28:in `brew'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.5.1/main.rb:116:in `<module:Homebrew>'
	from /home/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3.5.1/main.rb:17:in `<main>'
```

And the action part is:

```
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew formula version
        uses: dawidd6/action-homebrew-bump-formula@v3.5.1
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
```

`COMMITTER_TOKEN` is a custom PAT with `repo` and `workflow` scopes.

My initial idea was that I was using older version of action (3.5.1) and thought if I update to latest (3.7.0) that'll fix it but before doing that I noticed that `token` seems to be removed as part of [this commit](https://github.com/dawidd6/action-homebrew-bump-formula/commit/21cf14eea228e1194d1ccab1d98e8edf2df156d1#diff-8c2db00221aa4d66a91598201c26bb6b695ccd79084d53d9783d74f615dba898L63).

**Comment by dawidd6** [comment]
My bet: your token has a space at the beginning.

**Comment by khos2ow** [comment]
Yeah I noticed that extra space too, and wasn't sure how it ended up there in the log, but the same token still works on other part of the same ci.yaml file. (maybe other actions do some trimming?). Regardless thanks for the pointer, I'll double check.

**Comment by khos2ow** [comment]
That was an spot on bet! I rotated the token and made sure there was no space and it's working.
