### ISSUE TITLE
'Formulae must have a ref! (ArgumentError)'

### ISSUE THREAD

**Issue by jfoster** [dawidd6/action-homebrew-bump-formula#30]
Encountering this error when trying to use this on my personal homebrew tap, which includes both formulae and casks:
```
/usr/local/bin/brew tap jfoster/homebrew-tap
==> Tapping jfoster/tap
Cloning into '/usr/local/Homebrew/Library/Taps/jfoster/homebrew-tap'...
Tapped 5 casks and 7 formulae (44 files, 138.5KB).
/usr/local/bin/brew livecheck --quiet --newer-only --full-name --json --tap=jfoster/homebrew-tap
/usr/local/Homebrew/Library/Homebrew/formulary.rb:366:in `factory': Formulae must have a ref! (ArgumentError)
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:1645:in `[]'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:151:in `block in <module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:142:in `each'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:142:in `<module:Homebrew>'
	from /Users/runner/work/_actions/dawidd6/action-homebrew-bump-formula/v3/main.rb:18:in `<main>'
Error: Process completed with exit code 1.
```
Upon investigating [this line](https://github.com/dawidd6/action-homebrew-bump-formula/blob/76805f047e28754e28edb141e8d3dfa10ef374aa/main.rb#L151) it appears it simply does not expect a cask as an argument?
If this is intended behavior I'd suggested passing a `--formula` argument to livecheck to disable the checking of casks (I will submit a PR for this).
It would be awesome if this action could support casks, possibly making use of `bump-cask-pr`?

**Comment by dawidd6** [comment]
I don't think casks make use of livecheck. Given that much casks auto update, I don't know if it's a good idea to add this feature, but if anyone submits a PR for that I'll consider it.
