### ISSUE TITLE
Failing to update formula

### ISSUE THREAD

**Issue by nimrodkor** [dawidd6/action-homebrew-bump-formula#32]
Hey @dawidd6 , very cool action!

We're using it for checkov, and we recently launched checkov 2.0. since then every update fails. Example run:
https://github.com/bridgecrewio/checkov/runs/2316082261?check_suite_focus=true

Any ideas how we can tackle it?

**Comment by dawidd6** [comment]
Don't run this Action on push to master, only on tags.

**Comment by dawidd6** [comment]
Ye, really weird as it shouldn't.
