### ISSUE TITLE
Specifying which repo to make PR from

### ISSUE THREAD

**Issue by brendongo** [dawidd6/action-homebrew-bump-formula#33]
Is it possible to specify which homebrew-core fork to use when making a PR?

We have an org fork of homebrew-core: https://github.com/returntocorp/homebrew-core but the
bump-formula-pr action defaults to my personal fork: https://github.com/brendongo/homebrew-core. Is there anyway to tell the action to use the other fork?

**Comment by dawidd6** [comment]
I think it's doable, but it would require changes in `Homebrew/brew` to call GitHub API with additional `organization` parameter as described here:
https://docs.github.com/en/rest/reference/repos#create-a-fork

Can try to make required changes and PR them by yourself. Seems like a reasonable feature.

**Comment by brendongo** [comment]
Oh thanks! Will look into making those changes then!

**Comment by brendongo** [comment]
For reference opened ticket on homebrew/brew here: https://github.com/Homebrew/brew/issues/11143
