### ISSUE TITLE
refusing to allow a Personal Access Token to create or update workflow .github/workflows/autobump.yml without workflow scope

### ISSUE THREAD

**Issue by spacewander** [dawidd6/action-homebrew-bump-formula#40]
Thanks for this wonderful action, @dawidd6!

When I tried it, I got an error during pushing the code:
> refusing to allow a Personal Access Token to create or update workflow `.github/workflows/autobump.yml` without `workflow` scope

After I gave the workflow scope to the Personal Access Token, this action works well for me.

Maybe we should update the doc to mention the new scope?

**Comment by dawidd6** [comment]
Sure. Make a PR and we'll see.
