### ISSUE TITLE
Support for Homebrew Cask

### ISSUE THREAD

**Issue by MWin123** [dawidd6/action-homebrew-bump-formula#50]
Hi,

are there any plans to add support for [Homebrew casks](https://docs.brew.sh/Cask-Cookbook)?

According to [How to Open a Homebrew Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) there is a cask version of `brew bump-formula-pr` as well, i.e., `brew bump-cask-pr`.

**Comment by dawidd6** [comment]
No plans.

**Comment by eugenesvk** [comment]
Just FYI I've updated a cask fork of this fork https://github.com/eugenesvk/action-homebrew-bump-cask to a seemingly working state, but hopefully in the future something more official will be supported
