### ISSUE TITLE
Allow editing the Git user name and email

### ISSUE THREAD

**Issue by 5ouma** [dawidd6/action-homebrew-bump-formula#58]
This action automatically sets `user.name` and `user.email` to the owner.
https://github.com/dawidd6/action-homebrew-bump-formula/blob/855e1f15ce764f04bc85c01332245b8b6718a84f/main.rb#L58-L75

However, I want them to be `github-actions[bot]`.
I tried to set these environment variables, but it ignored them.
```
HOMEBREW_GIT_NAME: github-actions[bot]
HOMEBREW_GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
```
If any of these are set, it should respect these env.
- `HOMEBREW_GIT_NAME`
- `HOMEBREW_GIT_EMAIL`
- `GIT_AUTHOR_NAME`
- `GIT_AUTHOR_EMAIL`

In addition, I want to change the PR author to it, but I'm not sure how to do it. If anyone knows this, please let me know.

**Comment by dawidd6** [comment]
Please submit a PR to support this.
