### ISSUE TITLE
Tap `homebrew/core` with `--force` option

### ISSUE THREAD

**Issue by 5ouma** [dawidd6/action-homebrew-bump-formula#59]
Due to the change to download a JSON file of Formulae, tapping `homebrew/core` makes an error. Adding the `--force` option to the `brew tap` command should correct this issue.
Also, it might be good to tap `homebrew/core` only when `tap` is empty.

```ruby
if tap.blank?
  brew 'tap', 'homebrew/core', '--force'
else
  brew 'tap', tap
end
```

[The failed job on my GitHub Action](https://github.com/5ouma/homebrew-formula/actions/runs/7175194496/job/19539201199#step:3:1)

**Comment by dawidd6** [comment]
Could you submit a PR for this please?
