### ISSUE TITLE
Errors on formula with license

### ISSUE THREAD

**Issue by crunchtime-ali** [dawidd6/action-homebrew-bump-formula#8]
The errors for example on `brew livecheck --quiet --newer-only --full-name --json node-build` with the following errror whereas it works locally.

> /usr/local/Homebrew/Library/Homebrew/formulary.rb:38:in `rescue in load_formula': node-build: undefined method `license' for #<Class:0x00007fa494a76378> (FormulaUnreadableError)

Since your action uses the latest homebrew version and taps livecheck this shouldn't be a problem or am I missing the obvious here?

Here is an example of the error: https://github.com/crunchtime-ali/brew-formula-updater/runs/845486568

**Comment by dawidd6** [comment]
Hmm. Interesting. Seems to be fine in my repo: https://github.com/dawidd6/ba-bump/runs/845831009?check_suite_focus=true

**Comment by crunchtime-ali** [comment]
@dawidd6 I am trying to get into the GitHub actions game as well by investing this very issue. One question which I still can't answer is: How does your application know about the `brew` binary? You are using `node12` is used to run it but how could that know about the binary? I come from Jenkins- and GitLab CI town and still preach the `image` keyword to specify base images.

**Comment by dawidd6** [comment]
Actions runner uses `node` to run `main.js` JavaScript script first, then in that script I'm calling `brew ruby main.rb`, which executes this Ruby script in Homebrew environment.

**Comment by crunchtime-ali** [comment]
@dawidd6 I found the missing piece of missing information. The `macos-latest` runners have some software pre-installed which I did not know (https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md).

Now back to the missing license-method:
Since you update homebrew in the beginning the missing license method still should not be an issue. Maybe check which version of Homebrew is really checked out via `cd "$(brew --repository)" && git rev-parse HEAD && cd -`?

**Comment by dawidd6** [comment]
I already checked it. And it's the latest. Gonna try something else later.

**Comment by dawidd6** [comment]
Think it's fixed in https://github.com/dawidd6/action-homebrew-bump-formula/commit/fe3152818382c20ebfd1b82a05cb1932881fb5f0

**Comment by crunchtime-ali** [comment]
@dawidd6 Thank you. It looks like it fixed the issue in my repository.
What is the difference between triggering `brew update-reset` in `main.js` vs. later in `main.rb`

**Comment by dawidd6** [comment]
Yea, I suppose it it something like that.
