### ISSUE TITLE
Allow adding to the PR message

### ISSUE THREAD

**Issue by MasterOdin** [dawidd6/action-homebrew-bump-formula#9]
Right now, this action uses a [constant message](https://github.com/dawidd6/action-homebrew-bump-formula/blob/60d9960f25113b86056d0ffd5dfdd256d491de78/main.rb#L89) to append to the call to `bump-formula-pr`. Would you support adding the ability to put in a message in the yml that would then get prepended to this constant message? 

My use-case is that for asciidoc, I plan to move from running the action under my personal GH account to a bot account, but would like to have within the body of the PR a ping to my primary account.

**Comment by dawidd6** [comment]
Sure, that's a great idea. If you can/want, you can submit a PR for that feature or wait for me to implement it, but I'm a little occupied at the moment.

**Comment by dawidd6** [comment]
Done, see example test PR: https://github.com/dawidd6/homebrew-test/pull/256

If that's what the feature you wanted, please let me know and I'll release it.

**Comment by MasterOdin** [comment]
Yeah, that looks great! Thanks so much for this!

**Comment by dawidd6** [comment]
Released.
